version: '3.7'
services:
  sentry-redis:
    image: 'redis'
  sentry-postgres:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'sentry'
  sentry-config-generate-secret-key:
    image: 'sentry:9.1'
    command: 'sentry config generate-secret-key'
  sentry-upgrade:
    image: 'sentry:9.1'
    environment:
      SENTRY_SECRET_KEY: 'my-secret'
      SENTRY_POSTGRES_HOST: 'sentry-postgres'
      SENTRY_REDIS_HOST: 'sentry-redis'
    command: 'sentry upgrade'
  sentry:
    image: 'sentry:9.1'
    ports:
    - '9000:9000'
    environment:
      SENTRY_SECRET_KEY: 'my-secret'
      SENTRY_POSTGRES_HOST: 'sentry-postgres'
      SENTRY_REDIS_HOST: 'sentry-redis'